### ISSUE TITLE
[portal 2] sar_prevent_peti_materials_loading false-positive (?) when returning from compiled peti map

### ISSUE THREAD

**Issue by quat1024** [Blenderiste09/SourceAutoRecord#44]
Ok I need to preface this by saying I'm not sure if this is intended collateral from `sar_prevent_peti_materials_loading` - I mean, gee, it sure did prevent those materials from loading - but the description of the command says it "block[s] PeTI from loading its materials *outside of map editor*" and it seems to also prevent them from loading *inside* the map editor.

U can close this as invalid if it's an intended effect.

Anyway, if you *return from a compiled PeTI map with this setting on*, the materials are gone. In detail:

* Put `sar_prevent_peti_materials_loading 1` or `sar_fast_load_preset full` or whatever in autoexec
* Open portal 2
* Open puzzlemaker
* Observe how materials have successfully loaded. Nice
* Compile and open any map, the default map will do, just press the build&run button
* Press tab to return to the editor or use the pause menu option.
* Editor is all white, peti materials are gone 🦀

If the map is already compiled in the background BTW you can mash tab as much as you want, only triggering a new map load causes PeTI materials to disappear

(I'm also not a speedrunner lol I just use this for load time improvements and autojump for casual worshop play)

**Comment by PortalRex** [comment]
With the new update Valve fixed the memory leak so this cvar (sar_prevent_peti_materials_loading 1) will more than likely be removed, and this problem will be fixed.

**Comment by mlugg** [comment]
That is indeed a bug, there's code in there that's specifically meant to make sure that doesn't happen. I've experienced that bug before (because paths are slightly different on Linux), so I could probably fix it if necessary, however as Rex says, Valve have patched the memory leak themselves, so that cvar will almost certainly be removed in the 1.12.1 update anyway. You should be fine to just disable it for now since Valve have patched the issue

**Comment by mlugg** [comment]
cvar removed in 1.12.1
